services:
  db-petmap:
    image: postgis/postgis:16-master
    container_name: petmap_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: petmap
    networks:
      - petmap
    ports:
      - 0.0.0.0:5430:5432
    volumes:
      - petmap-db_pstgre_gis:/var/lib/postgresql/data
  db-visor-petmap:
    image: adminer
    container_name: adminer_petmap
    ports:
      - "8014:8080"
    networks:
      - petmap
    depends_on:
      db-petmap:
        condition: service_started
        restart: true
    environment:
      ADMINER_PLUGIN: 'table-indexes-structure tables-filter tinymce'
      ADMINER_DESIGN: 'dracula'
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_USER: root
      ADMINER_DEFAULT_USER_PASSWORD: root
      ADMINER_DEFAULT_SERVER: db-postgre
      ADMINER_DEFAULT_DB_NAME: petmap

  media-storage-petmap:
    image: dxflrs/garage:v2.0.0
    container_name: media-storage-petmap
    userns_mode: "keep-id"
    environment:
      RUST_LOG: garage=debug
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
    network_mode: "host"
    volumes:
      - ./garage/etc/garage.toml:/etc/garage.toml
      - ./garage/var/lib/garage/meta:/var/lib/garage/meta
      - ./garage/var/lib/garage/data:/var/lib/garage/data

volumes:
  petmap-db_pstgre_gis:

networks:
  petmap:
